---


name: Renovate
on: # yamllint disable-line rule:truthy
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.3
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GH_PAT }}
    env:
      LOG_LEVEL: 'debug'
